export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagaced

for f in "$HOME"/.bash.d/*; do
  [ -r "$f" ] && . "$f"
done

source /usr/local/bin/virtualenvwrapper.sh

export IPYTHON=1
export PATH=$PATH:/usr/local/sbin:/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin
